import type { IconType } from 'react-icons'
import {
  SiJavascript,
  SiTypescript,
  SiPython,
  SiCplusplus,
  SiPhp,
  SiMysql,
  SiMongodb,
  SiReact,
  SiHtml5,
  SiCss,
  SiSharp,
  SiNodedotjs,
  SiExpress,
  SiFastapi,
  SiLaravel,
  SiFlutter,
  SiDart,
  SiUnity,
  SiNumpy,
  SiTensorflow,
  SiRaspberrypi,
  SiGit,
  SiGithub,
  SiPostman,
  SiLinux,
  SiOpenjdk,
  SiDotnet,
  SiOpencv,
  SiMediapipe,
  SiAngular,
} from 'react-icons/si'
import {
  FiCode,
  FiLock,
  FiServer,
  FiDatabase,
  FiCpu,
  FiBox,
  FiEye,
  FiLayers,
  FiGrid,
  FiPenTool,
} from 'react-icons/fi'

const registry: Record<string, IconType> = {
  javascript: SiJavascript,
  typescript: SiTypescript,
  python: SiPython,
  cpp: SiCplusplus,
  php: SiPhp,
  mysql: SiMysql,
  mongodb: SiMongodb,
  react: SiReact,
  angularjs: SiAngular,
  html5: SiHtml5,
  css3: SiCss,
  nodejs: SiNodedotjs,
  express: SiExpress,
  fastapi: SiFastapi,
  laravel: SiLaravel,
  blade: SiLaravel,
  flutter: SiFlutter,
  dart: SiDart,
  unity: SiUnity,
  numpy: SiNumpy,
  tensorflow: SiTensorflow,
  raspberrypi: SiRaspberrypi,
  git: SiGit,
  github: SiGithub,
  postman: SiPostman,
  linux: SiLinux,
  java: SiOpenjdk,
  dotnet: SiDotnet,
  aspnet: SiDotnet,
  csharp: SiSharp,
  sql: FiDatabase,
  plsql: FiDatabase,
  sqlserver: FiDatabase,
  nosql: FiDatabase,
  javafx: SiOpenjdk,
  oop: FiCode,
  dsa: FiLayers,
  mvc: FiGrid,
  softwaredesign: FiPenTool,
  machinelearning: FiCpu,
  deeplearning: FiCpu,
  jwt: FiLock,
  rbac: FiLock,
  restapi: FiServer,
  mqtt: FiServer,
  rfid: FiCpu,
  grovepi: FiCpu,
  arfoundation: FiBox,
  xrtoolkit: FiBox,
  vuforia: FiBox,
  mixedreality: FiBox,
  vr: FiBox,
  ar: FiBox,
  opencv: SiOpencv,
  mediapipe: SiMediapipe,
  computervision: FiEye,
  imageclassification: FiCpu,
  objectdetection: FiCpu,
  autoencoders: FiCpu,
}

export function getSkillIcon(key: string): IconType {
  return registry[key] ?? FiCode
}
